name: marketdo_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  get_storage: ^2.1.1
  flutter_iconly: ^1.0.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  getwidget: ^3.0.1
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  location: ^4.4.0
  flutter_easyloading: ^3.0.5
  firebase_storage: ^11.1.1
  firebase_auth: ^4.4.2
  image_picker: ^0.8.7+4
  get: ^4.6.5
  url_launcher: ^6.1.11
  clipboard: ^0.1.3
  tab_indicator_styler: ^2.0.0
  intl: ^0.18.0
  flutterfire_ui: ^0.4.3+20
  awesome_number_picker: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/marketdoLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
