name: marketdo_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  awesome_number_picker: ^0.0.4
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  cloud_firestore: ^4.5.0
  dots_indicator: ^3.0.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.1
  flutter_easyloading: ^3.0.5
  flutter_iconly: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutterfire_ui: ^0.4.3+20
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  getwidget: ^3.0.1
  google_maps_flutter: ^2.3.1
  image_picker: ^0.8.7+4
  intl: ^0.18.0
  location: ^4.4.0
  tab_indicator_styler: ^2.0.0
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.1.2
  email_validator: ^2.1.17
  flutter_slidable: ^3.0.0
  receipt: ^0.0.1
  font_awesome_flutter: ^10.5.0
  pdf: ^3.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/marketdoLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/marketdoLogo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
